version: "3"
services:
  web:
    image: flask
    restart: always
    build: ./
    env_file: .env
    ports:
      - "8000:8000"
    command: gunicorn -w 2 -b :8000 app:create_app()
    depends_on:
      - db

  client:
    image: webpack
    build:
      context: ./client
    ports:
      - "8080:8080"
    env_file: .env
    links:
      - web

  db:
    image: postgres:10
    restart: always
    env_file: .env
    ports:
      - 5432
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data

  nginx:
    restart: always
    build: ./nginx
    ports:
    - "80:80"
    depends_on:
    - web
