version: "3"
services:
  web:
    image: flask
    restart: always
    build: ./
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    image: webpack
    build:
      context: ./client
    ports:
      - "8080:8080"
    env_file: .env
    links:
      - web

  db:
    image: postgres:10
    restart: always
    env_file: db.env
    ports:
      - 5432
